### PR TITLE
Discord Overlay

### PR DESCRIPTION
**Pull request by OrangeDrangon**
Oh and some formatting got changed so lots of changes XD

Main changes are at main.js:757

There is a related issue but don't know how to link them here is a link: https://github.com/freshgarlicblocks/freshgarlicblocks-website/issues/17

### CODE REVIEW

**Comment by OrangeDrangon** [comment]
https://github.com/freshgarlicblocks/freshgarlicblocks-website/issues/17

**Comment by nuc1e4r5n4k3** [comment]
Lot of changes in this PR (most of them formatting). Need to go over the entire thing carefully before I merge it in.

**Comment by OrangeDrangon** [comment]
I deleted 3 lines and added like 2 my ide messed everything up

**Comment by OrangeDrangon** [comment]
Recommitted with the changes and made sure not to mess up formatting.

**Comment by OrangeDrangon** [comment]
How to not view white space changes on github...

```
Ever have someone push a commit that involves a lot of real changes mixed in with a bunch of less-meaningful whitespace? Add ?w=1 to the URL to see the diff with whitespace ignored.
```

**Review by nuc1e4r5n4k3 — APPROVED** [review]
Approved

**Pull request merged**
